--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/RulesBook
build-by-default: true
branches:
- master
projects:
  RulesBook:
    path: ""
    libs:
      - src: cooldogepm/libBook/libBook
        version: 0.0.2
...
