---
name: RulesNoteBook
version: 0.0.1
main: NurAzliYT\NoteRulesBook\Main
api: 5.0.0
description: Show preview rules book when a player first joins the server or uses /rulesbook command
author: NurAzliYT

commands:
  rulesnotebook:
    description: Show preview rules book
    aliases: [rules, rulesbook, rulesnote]
    permission: rulesnotebook.command
permissions:
  rulesnotebook.command:
    description: Permission for /rulesnotebook
    default: true
...
